services:
  memorial-gallery:
    build:
      context: ./app
    ports:
      - "8010:8080"
    env_file:
      - .env
    environment:
      - TITLE=Memorial Gallery
      - THUMBNAIL_MAX_PX=480
      - DISPLAY_MAX_PX=1280
      - SLIDESHOW_INTERVAL_SEC=6
    volumes:
      - ./media:/data/media
      - ./site:/app/site
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:2024.9.1
    restart: unless-stopped
    command: tunnel --config /etc/cloudflared/config.yml run
    depends_on:
      memorial-gallery:
        condition: service_started
    volumes:
      - ./cloudflared:/etc/cloudflared:ro
    profiles:
      - cloudflare
